/**
 * Public installer endpoint.
 *
 * This route is intentionally self-contained because it has to generate a
 * complete installer script for Linux, macOS, or Windows from a one-time
 * install token. It is also one of the few routes that is expected to be
 * called before an agent exists as a running service.
 */
import express from "express";
import config from "../config.js";
import { dbOps } from "../db/index.js";
import { resolveBaseUrl } from "../utils/base-url.js";
import { getSetting } from "../utils/settings.js";
import { decryptSecret, generateToken, hashToken, protectToken } from "../utils/tokens.js";

const router = express.Router();

function isHttps(req) {
  return req.secure === true;
}

// Quote a value for POSIX shell scripts generated by this route.
function shellQuote(value) {
  return `'${String(value ?? "").replace(/'/g, `'\"'\"'`)}'`;
}

// Quote a value for PowerShell scripts generated by this route.
function psQuote(value) {
  return `'${String(value ?? "").replace(/'/g, "''")}'`;
}

// Keep schedule values predictable because they are embedded in generated scripts.
function sanitizeScheduleTime(value) {
  const raw = String(value || "");
  return /^([01]\d|2[0-3]):[0-5]\d$/.test(raw) ? raw : "03:00";
}

// Poll interval can come from DB settings or config. Normalize it before use.
function sanitizePollSeconds(value, fallback) {
  const parsed = Number.parseInt(value, 10);
  if (Number.isFinite(parsed) && parsed > 0) {
    return parsed;
  }
  const fallbackParsed = Number.parseInt(fallback, 10);
  return Number.isFinite(fallbackParsed) && fallbackParsed > 0 ? fallbackParsed : 15;
}

// Some installations may still be in a migration window. Fail closed here.
function extractAgentApiToken(agent) {
  try {
    return agent.agent_api_token_enc ? decryptSecret(agent.agent_api_token_enc) : agent.agent_api_token;
  } catch {
    return null;
  }
}

// Once a token is used successfully we persist it in the protected format only.
async function persistInstallToken(agent, installToken) {
  const protectedInstallToken = protectToken(installToken);
  await dbOps.run(
    "UPDATE agents SET install_token = NULL, install_token_hash = ?, install_token_enc = ? WHERE id = ?",
    [protectedInstallToken.hash, protectedInstallToken.encrypted, agent.id]
  );
  agent.install_token = null;
  agent.install_token_hash = protectedInstallToken.hash;
  agent.install_token_enc = protectedInstallToken.encrypted;
}

// If an agent has never connected yet we can safely rotate its API token here.
async function ensureInstallableAgentApiToken(agent) {
  const existingToken = extractAgentApiToken(agent);
  if (existingToken) {
    return existingToken;
  }
  if (agent.last_seen_at) {
    return null;
  }

  const agentApiToken = generateToken(32);
  const protectedAgentApiToken = protectToken(agentApiToken);
  await dbOps.run(
    "UPDATE agents SET agent_api_token = NULL, agent_api_token_hash = ?, agent_api_token_enc = ? WHERE id = ?",
    [protectedAgentApiToken.hash, protectedAgentApiToken.encrypted, agent.id]
  );
  agent.agent_api_token = null;
  agent.agent_api_token_hash = protectedAgentApiToken.hash;
  agent.agent_api_token_enc = protectedAgentApiToken.encrypted;
  return agentApiToken;
}

// Shared shell helpers injected into both Linux and macOS installer templates.
function buildShellBundleVerificationHelpers() {
  return `header_value() {
  key="$1"
  tr -d '\\r' < "$TMP_HEADERS" | awk -F': ' -v wanted="$key" 'tolower($1)==tolower(wanted){print $2}' | tail -n 1
}

python_sha256() {
  "\${PYTHON_BIN}" - "$1" <<'PY'
import hashlib
import sys

digest = hashlib.sha256()
with open(sys.argv[1], "rb") as handle:
    while True:
        chunk = handle.read(1024 * 1024)
        if not chunk:
            break
        digest.update(chunk)
print(digest.hexdigest())
PY
}

python_hmac() {
  "\${PYTHON_BIN}" - "$1" "$2" <<'PY'
import hashlib
import hmac
import sys

print(hmac.new(sys.argv[2].encode("utf-8"), sys.argv[1].encode("utf-8"), hashlib.sha256).hexdigest())
PY
}

download_bundle() {
  curl -fsSLo "$TMP_BUNDLE" -D "$TMP_HEADERS" \\
    -H "Authorization: Bearer $AGENT_API_TOKEN" \\
    "$DASHBOARD_URL/agent/latest.tar.gz"
}

verify_bundle() {
  expected_sha="$(header_value X-Bundle-Sha256)"
  expected_sig="$(header_value X-Bundle-Signature)"
  if [ -z "$expected_sha" ] || [ -z "$expected_sig" ]; then
    echo "Missing bundle integrity headers." >&2
    exit 1
  fi

  actual_sha="$(python_sha256 "$TMP_BUNDLE")"
  if [ "$actual_sha" != "$expected_sha" ]; then
    echo "Bundle checksum mismatch." >&2
    exit 1
  fi

  actual_sig="$(python_hmac "$expected_sha" "$AGENT_API_TOKEN")"
  if [ "$actual_sig" != "$expected_sig" ]; then
    echo "Bundle signature mismatch." >&2
    exit 1
  fi
}
`;
}

// Linux installer: install prerequisites, fetch the bundle, write config, and wire services.
function buildLinuxScript(agent, baseUrl, agentApiToken, scheduleEnabled, scheduleTime, pollSeconds) {
  return `#!/bin/sh
set -eu

DASHBOARD_URL=${shellQuote(baseUrl)}
AGENT_ID=${shellQuote(agent.id)}
DISPLAY_NAME=${shellQuote(agent.display_name)}
AGENT_API_TOKEN=${shellQuote(agentApiToken)}
POLL_SECONDS=${pollSeconds}
SCHEDULE_ENABLED=${scheduleEnabled}
SCHEDULE_TIME=${shellQuote(scheduleTime)}

INSTALL_DIR="/opt/agentautoupdate"
APP_DIR="$INSTALL_DIR/app"
LOG_DIR="$INSTALL_DIR/logs"
VENV_DIR="$INSTALL_DIR/venv"
CLI_PATH="/usr/local/bin/agentautoupdate"
TMP_BUNDLE="/tmp/agentautoupdate-latest.tar.gz"
TMP_HEADERS="/tmp/agentautoupdate-latest.headers"
PYTHON_BIN=""

mkdir -p "$INSTALL_DIR" "$LOG_DIR"
chmod 700 "$INSTALL_DIR" "$LOG_DIR"

install_requirements() {
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -y
    apt-get install -y python3 python3-venv python3-pip curl ca-certificates openssl tar
  elif command -v dnf >/dev/null 2>&1; then
    dnf -y install python3 python3-pip python3-virtualenv curl ca-certificates openssl tar
  elif command -v yum >/dev/null 2>&1; then
    yum -y install python3 python3-pip python3-virtualenv curl ca-certificates openssl tar
  elif command -v pacman >/dev/null 2>&1; then
    pacman -Sy --noconfirm --needed python python-pip curl ca-certificates openssl tar
  else
    echo "Unsupported distribution: apt, dnf, yum or pacman required." >&2
    exit 1
  fi
}

detect_python() {
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python3)"
  elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python)"
  else
    echo "Python 3 is required." >&2
    exit 1
  fi
}

${buildShellBundleVerificationHelpers()}

install_requirements
detect_python
"$PYTHON_BIN" -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --upgrade pip --quiet

download_bundle
verify_bundle

rm -rf "$APP_DIR"
mkdir -p "$APP_DIR"
tar -xzf "$TMP_BUNDLE" -C "$APP_DIR"
"$VENV_DIR/bin/pip" install -r "$APP_DIR/requirements.txt" --quiet

umask 077
cat > "$INSTALL_DIR/config.json" <<JSON
{
  "agentId": "$AGENT_ID",
  "displayName": "$DISPLAY_NAME",
  "dashboardUrl": "$DASHBOARD_URL",
  "agentApiToken": "$AGENT_API_TOKEN",
  "pollIntervalSeconds": $POLL_SECONDS,
  "schedule": {
    "enabled": ${scheduleEnabled},
    "dailyTime": "$SCHEDULE_TIME"
  }
}
JSON

cat > "$CLI_PATH" <<'EOF'
#!/bin/sh
exec /opt/agentautoupdate/venv/bin/python /opt/agentautoupdate/app/agent_cli.py "$@"
EOF
chmod 755 "$CLI_PATH"

cat > /etc/systemd/system/agentautoupdate.service <<'EOF'
[Unit]
Description=Agent Auto Update Poller
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/opt/agentautoupdate
ExecStart=/opt/agentautoupdate/venv/bin/python /opt/agentautoupdate/app/agent_poller.py
Restart=always
RestartSec=5
Environment=PYTHONUNBUFFERED=1
UMask=0077

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/agentautoupdate-run.service <<'EOF'
[Unit]
Description=Agent Auto Update Runner
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=root
Group=root
WorkingDirectory=/opt/agentautoupdate
ExecStart=/opt/agentautoupdate/venv/bin/python /opt/agentautoupdate/app/agent_runner.py --run-once
Environment=PYTHONUNBUFFERED=1
UMask=0077
EOF

cat > /etc/systemd/system/agentautoupdate-run.timer <<EOF
[Unit]
Description=Agent Auto Update Schedule

[Timer]
OnCalendar=*-*-* $SCHEDULE_TIME:00
Persistent=true
Unit=agentautoupdate-run.service

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now agentautoupdate.service

if [ "$SCHEDULE_ENABLED" = "1" ]; then
  systemctl enable --now agentautoupdate-run.timer
else
  systemctl disable --now agentautoupdate-run.timer || true
fi

"$VENV_DIR/bin/python" "$APP_DIR/agent_poller.py" --once || true
rm -f "$TMP_BUNDLE" "$TMP_HEADERS"

echo "Agent installed for Linux."
echo "CLI:    $CLI_PATH"
echo "Status: systemctl status agentautoupdate.service"
`;
}

// macOS installer: same flow as Linux, but backed by launchd instead of systemd.
function buildMacOSScript(agent, baseUrl, agentApiToken, scheduleEnabled, scheduleTime, pollSeconds) {
  const [hour, minute] = scheduleTime.split(":").map((value) => Number.parseInt(value, 10) || 0);
  return `#!/bin/bash
set -euo pipefail

DASHBOARD_URL=${shellQuote(baseUrl)}
AGENT_ID=${shellQuote(agent.id)}
DISPLAY_NAME=${shellQuote(agent.display_name)}
AGENT_API_TOKEN=${shellQuote(agentApiToken)}
POLL_SECONDS=${pollSeconds}
SCHEDULE_ENABLED=${scheduleEnabled}
SCHEDULE_TIME=${shellQuote(scheduleTime)}
SCHEDULE_HOUR=${hour}
SCHEDULE_MINUTE=${minute}

INSTALL_DIR="/Library/Application Support/AgentAutoUpdate"
APP_DIR="$INSTALL_DIR/app"
LOG_DIR="$INSTALL_DIR/logs"
VENV_DIR="$INSTALL_DIR/venv"
CLI_PATH="/usr/local/bin/agentautoupdate"
POLLER_PLIST="/Library/LaunchDaemons/com.agentautoupdate.poller.plist"
RUNNER_PLIST="/Library/LaunchDaemons/com.agentautoupdate.runner.plist"
TMP_BUNDLE="/tmp/agentautoupdate-latest.tar.gz"
TMP_HEADERS="/tmp/agentautoupdate-latest.headers"
PYTHON_BIN=""

mkdir -p "$INSTALL_DIR" "$LOG_DIR"
chmod 700 "$INSTALL_DIR" "$LOG_DIR"

detect_python() {
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python3)"
  elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python)"
  else
    echo "Python 3 not found. Install Xcode Command Line Tools first: xcode-select --install" >&2
    exit 1
  fi
}

${buildShellBundleVerificationHelpers()}

detect_python
"$PYTHON_BIN" -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --upgrade pip --quiet

download_bundle
verify_bundle

rm -rf "$APP_DIR"
mkdir -p "$APP_DIR"
tar -xzf "$TMP_BUNDLE" -C "$APP_DIR"
"$VENV_DIR/bin/pip" install -r "$APP_DIR/requirements.txt" --quiet

umask 077
cat > "$INSTALL_DIR/config.json" <<JSON
{
  "agentId": "$AGENT_ID",
  "displayName": "$DISPLAY_NAME",
  "dashboardUrl": "$DASHBOARD_URL",
  "agentApiToken": "$AGENT_API_TOKEN",
  "pollIntervalSeconds": $POLL_SECONDS,
  "schedule": {
    "enabled": ${scheduleEnabled},
    "dailyTime": "$SCHEDULE_TIME"
  }
}
JSON

cat > "$CLI_PATH" <<'EOF'
#!/bin/sh
exec "/Library/Application Support/AgentAutoUpdate/venv/bin/python" "/Library/Application Support/AgentAutoUpdate/app/agent_cli.py" "$@"
EOF
chmod 755 "$CLI_PATH"

cat > "$POLLER_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.agentautoupdate.poller</string>
  <key>ProgramArguments</key>
  <array>
    <string>$INSTALL_DIR/venv/bin/python</string>
    <string>$INSTALL_DIR/app/agent_poller.py</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>$INSTALL_DIR</string>
  <key>StandardOutPath</key>
  <string>$LOG_DIR/poller.log</string>
  <key>StandardErrorPath</key>
  <string>$LOG_DIR/poller.err</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PYTHONUNBUFFERED</key>
    <string>1</string>
  </dict>
</dict>
</plist>
PLIST

cat > "$RUNNER_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.agentautoupdate.runner</string>
  <key>ProgramArguments</key>
  <array>
    <string>$INSTALL_DIR/venv/bin/python</string>
    <string>$INSTALL_DIR/app/agent_runner.py</string>
    <string>--run-once</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key>
    <integer>$SCHEDULE_HOUR</integer>
    <key>Minute</key>
    <integer>$SCHEDULE_MINUTE</integer>
  </dict>
  <key>WorkingDirectory</key>
  <string>$INSTALL_DIR</string>
  <key>StandardOutPath</key>
  <string>$LOG_DIR/runner.log</string>
  <key>StandardErrorPath</key>
  <string>$LOG_DIR/runner.err</string>
</dict>
</plist>
PLIST

chmod 644 "$POLLER_PLIST" "$RUNNER_PLIST"
launchctl bootout system "$POLLER_PLIST" >/dev/null 2>&1 || true
launchctl bootstrap system "$POLLER_PLIST"

if [ "$SCHEDULE_ENABLED" = "1" ]; then
  launchctl bootout system "$RUNNER_PLIST" >/dev/null 2>&1 || true
  launchctl bootstrap system "$RUNNER_PLIST"
else
  launchctl bootout system "$RUNNER_PLIST" >/dev/null 2>&1 || true
fi

"$VENV_DIR/bin/python" "$APP_DIR/agent_poller.py" --once || true
rm -f "$TMP_BUNDLE" "$TMP_HEADERS"

echo "Agent installed for macOS."
echo "CLI:    $CLI_PATH"
echo "Status: sudo launchctl print system/com.agentautoupdate.poller"
`;
}

// Windows installer script generated as PowerShell.
function buildWindowsScript(agent, baseUrl, agentApiToken, scheduleEnabled, scheduleTime, pollSeconds) {
  return `# Agent Auto Update — Windows Installer
$ErrorActionPreference = 'Stop'

$DASHBOARD_URL = ${psQuote(baseUrl)}
$AGENT_ID = ${psQuote(agent.id)}
$DISPLAY_NAME = ${psQuote(agent.display_name)}
$API_TOKEN = ${psQuote(agentApiToken)}
$POLL_SECONDS = ${pollSeconds}
$SCHEDULE_ENABLED = ${scheduleEnabled}
$SCHEDULE_TIME = ${psQuote(scheduleTime)}

$INSTALL_DIR = 'C:\\ProgramData\\AgentAutoUpdate'
$APP_DIR = Join-Path $INSTALL_DIR 'app'
$LOG_DIR = Join-Path $INSTALL_DIR 'logs'
$VENV_DIR = Join-Path $INSTALL_DIR 'venv'
$CLI_PATH = Join-Path $INSTALL_DIR 'agentautoupdate.cmd'
$TMP_BUNDLE = Join-Path $env:TEMP 'agentautoupdate-latest.tar.gz'
$POLLER_TASK = 'AgentAutoUpdate Poller'
$RUNNER_TASK = 'AgentAutoUpdate Runner'

function Get-PythonCommand {
    $python = Get-Command python -ErrorAction SilentlyContinue
    if (-not $python) {
        throw 'Python 3 is required on Windows 11. Install Python 3.12+ first.'
    }
    return $python.Source
}

function Get-HmacSha256Hex([string]$Value, [string]$Secret) {
    $hmac = [System.Security.Cryptography.HMACSHA256]::new([System.Text.Encoding]::UTF8.GetBytes($Secret))
    try {
        $bytes = $hmac.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Value))
        return ([BitConverter]::ToString($bytes)).Replace('-', '').ToLowerInvariant()
    } finally {
        $hmac.Dispose()
    }
}

New-Item -ItemType Directory -Force -Path $INSTALL_DIR,$LOG_DIR | Out-Null
$python = Get-PythonCommand

& $python -m venv $VENV_DIR
& "$VENV_DIR\\Scripts\\pip.exe" install --upgrade pip --quiet

$response = Invoke-WebRequest -Uri "$DASHBOARD_URL/agent/latest.tar.gz" \`
    -Headers @{ Authorization = "Bearer $API_TOKEN" } \`
    -OutFile $TMP_BUNDLE -UseBasicParsing -PassThru

$expectedSha = ($response.Headers['X-Bundle-Sha256'] | Select-Object -First 1).ToString().ToLowerInvariant()
$expectedSig = ($response.Headers['X-Bundle-Signature'] | Select-Object -First 1).ToString().ToLowerInvariant()
if (-not $expectedSha -or -not $expectedSig) {
    throw 'Missing bundle integrity headers.'
}

$actualSha = (Get-FileHash -Path $TMP_BUNDLE -Algorithm SHA256).Hash.ToLowerInvariant()
if ($actualSha -ne $expectedSha) {
    throw 'Bundle checksum mismatch.'
}

$actualSig = Get-HmacSha256Hex -Value $expectedSha -Secret $API_TOKEN
if ($actualSig -ne $expectedSig) {
    throw 'Bundle signature mismatch.'
}

if (Test-Path $APP_DIR) {
    Remove-Item $APP_DIR -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $APP_DIR | Out-Null
tar -xzf $TMP_BUNDLE -C $APP_DIR
& "$VENV_DIR\\Scripts\\pip.exe" install -r "$APP_DIR\\requirements.txt" --quiet

@{
    agentId = $AGENT_ID
    displayName = $DISPLAY_NAME
    dashboardUrl = $DASHBOARD_URL
    agentApiToken = $API_TOKEN
    pollIntervalSeconds = $POLL_SECONDS
    schedule = @{ enabled = ([bool]($SCHEDULE_ENABLED -eq 1)); dailyTime = $SCHEDULE_TIME }
} | ConvertTo-Json -Depth 5 | Set-Content -Path (Join-Path $INSTALL_DIR 'config.json') -Encoding UTF8

@"
@echo off
"$VENV_DIR\\Scripts\\python.exe" "$APP_DIR\\agent_cli.py" %*
"@ | Set-Content -Path $CLI_PATH -Encoding Ascii

$pollerAction = New-ScheduledTaskAction -Execute "$VENV_DIR\\Scripts\\python.exe" -Argument "$APP_DIR\\agent_poller.py"
$pollerTrigger = New-ScheduledTaskTrigger -AtStartup
$taskSettings = New-ScheduledTaskSettingsSet -RestartCount 10 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew
$principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
Register-ScheduledTask -TaskName $POLLER_TASK -Action $pollerAction -Trigger $pollerTrigger -Settings $taskSettings -Principal $principal -Force | Out-Null

if ($SCHEDULE_ENABLED -eq 1) {
    $runnerAction = New-ScheduledTaskAction -Execute "$VENV_DIR\\Scripts\\python.exe" -Argument "$APP_DIR\\agent_runner.py --run-once"
    $runnerTrigger = New-ScheduledTaskTrigger -Daily -At $SCHEDULE_TIME
    Register-ScheduledTask -TaskName $RUNNER_TASK -Action $runnerAction -Trigger $runnerTrigger -Settings $taskSettings -Principal $principal -Force | Out-Null
} else {
    Unregister-ScheduledTask -TaskName $RUNNER_TASK -Confirm:$false -ErrorAction SilentlyContinue
}

Start-ScheduledTask -TaskName $POLLER_TASK
& "$VENV_DIR\\Scripts\\python.exe" "$APP_DIR\\agent_poller.py" --once
Remove-Item $TMP_BUNDLE -Force -ErrorAction SilentlyContinue

Write-Host 'Agent installed for Windows.'
Write-Host "CLI:    $CLI_PATH"
Write-Host "Status: Get-ScheduledTask -TaskName '$POLLER_TASK'"
`;
}

router.get("/", async (req, res) => {
  try {
    // A missing token should look like a regular 404 to avoid exposing the endpoint.
    const { token, platform: rawPlatform } = req.query || {};
    if (!token) {
      res.status(404).send("Not found");
      return;
    }
    if (!config.allowHttpInstall && !isHttps(req)) {
      res.status(403).send("HTTPS required");
      return;
    }

    const agent = await dbOps.get(
      "SELECT * FROM agents WHERE install_token_hash = ? OR install_token = ?",
      [hashToken(token), token]
    );
    if (!agent) {
      res.status(404).send("Not found");
      return;
    }

    if (!agent.install_token_enc || agent.install_token) {
      await persistInstallToken(agent, token);
    }

    const agentApiToken = await ensureInstallableAgentApiToken(agent);
    if (!agentApiToken) {
      res.status(500).send("Agent token unavailable");
      return;
    }

    const platform = ["macos", "windows"].includes(rawPlatform) ? rawPlatform : "linux";
    const baseUrl = agent.install_base_url
      ? agent.install_base_url.replace(/\/$/, "")
      : (await resolveBaseUrl()).replace(/\/$/, "");
    const scheduleEnabled = agent.schedule_enabled ? 1 : 0;
    const scheduleTime = sanitizeScheduleTime(agent.schedule_daily_time);
    const defaultPoll = await getSetting("defaultPollSeconds");
    const pollSeconds = sanitizePollSeconds(defaultPoll, config.agentDefaultPollSeconds);

    res.setHeader("Cache-Control", "no-store");

    if (platform === "windows") {
      res.setHeader("Content-Type", "text/plain; charset=utf-8");
      res.setHeader("Content-Disposition", "inline; filename=aaul-install.ps1");
      res.send(
        buildWindowsScript(agent, baseUrl, agentApiToken, scheduleEnabled, scheduleTime, pollSeconds)
      );
      return;
    }

    res.setHeader("Content-Type", "text/x-sh; charset=utf-8");
    if (platform === "macos") {
      res.send(
        buildMacOSScript(agent, baseUrl, agentApiToken, scheduleEnabled, scheduleTime, pollSeconds)
      );
      return;
    }

    res.send(
      buildLinuxScript(agent, baseUrl, agentApiToken, scheduleEnabled, scheduleTime, pollSeconds)
    );
  } catch (error) {
    console.error("[install] Failed to generate installer", {
      message: error?.message || String(error),
      stack: error?.stack || null,
      query: {
        hasToken: Boolean(req.query?.token),
        platform: req.query?.platform || null
      }
    });
    if (!res.headersSent) {
      res.status(500).send("Failed to generate installer");
    }
  }
});

export default router;
